[project]
name = "ansible-role-borgmatic"
version = "0.1.0"
description = "Project for ansible Depends"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.9.0",
    "ansible-lint>=25.8.1",
    "molecule-docker>=2.1.0",
    "molecule>=25.7.0",
]
