- name: Install Borgbackup and jq
  ansible.builtin.package:
    name:
      - borgbackup
      - jq
      - cron
    state: present

- name: Install pipx
  ansible.builtin.package:
    name: pipx
    state: present

- name: Install borgmatic via pipx
  become: true
  community.general.pipx:
    name: borgmatic
    state: present

- name: Ensure Borgmatic Config Folder
  become: true
  ansible.builtin.file:
    path: "/etc/borgmatic"
    state: directory
    owner: "{{ borgbackup_user.name }}"
    group: "{{ borgbackup_user.name }}"
    mode: 0770
